/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Sanctuary Quietude Primary Color System
        "surface-tint": "#316766",
        "surface-container-highest": "#d6e6e2",
        "outline": "#707978",
        "on-primary-fixed-variant": "#144f4e",
        "on-tertiary-container": "#bccac4",
        "secondary": "#3e6659",
        "surface": "#edfdf9",
        "tertiary-container": "#485651",
        "primary-fixed-dim": "#9ad0cf",
        "safety-emergency-subtle": "#FBEAEA",
        "tertiary": "#313f3a",
        "surface-container-high": "#dcece8",
        "bg-canvas": "#F5F8F6",
        "secondary-fixed-dim": "#a4d0c0",
        "primary-fixed": "#b6edeb",
        "primary": "#024343",
        "surface-container-low": "#e7f7f3",
        "secondary-fixed": "#c0ecdb",
        "text-primary": "#243333",
        "on-surface-variant": "#404848",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#245b5a",
        "background": "#edfdf9",
        "on-primary": "#ffffff",
        "surface-container": "#e1f1ed",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "border-subtle": "#D9E4DF",
        "secondary-container": "#c0ecdb",
        "surface-crisp": "#FFFFFF",
        "surface-dim": "#cdddda",
        "inverse-surface": "#253331",
        "surface-variant": "#d6e6e2",
        "text-secondary": "#61706D",
        "on-primary-container": "#9ad1cf",
        "on-tertiary-fixed-variant": "#3c4a45",
        "on-tertiary-fixed": "#111e1a",
        "on-secondary-fixed": "#002018",
        "surface-bright": "#edfdf9",
        "inverse-primary": "#9ad0cf",
        "on-background": "#101e1c",
        "safety-emergency": "#C85C5C",
        "on-error-container": "#93000a",
        "on-surface": "#101e1c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#446c5f",
        "tertiary-fixed-dim": "#bbcac3",
        "tertiary-fixed": "#d7e6df",
        "bg-subtle": "#EAF2EE",
        "on-primary-fixed": "#00201f",
        "error": "#ba1a1a",
        "inverse-on-surface": "#e4f4f0",
        "on-secondary-fixed-variant": "#264e42",
        "outline-variant": "#bfc8c7",

        // Backward compatibility mappings
        sand: {
          50: "#F5F8F6",
          100: "#EAF2EE",
          200: "#D9E4DF",
          300: "#cdddda",
        },
        sage: {
          50: "#e7f7f3",
          100: "#DCEBE4",
          200: "#c0ecdb",
          300: "#a4d0c0",
          500: "#7FA99A",
          600: "#3e6659",
          700: "#245b5a",
          800: "#024343",
          900: "#101e1c",
        },
        clay: {
          50: "#FBEAEA",
          400: "#e07a7a",
          500: "#C85C5C",
          600: "#C85C5C",
          700: "#AA4848",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-sm": "1rem",
        gutter: "1.5rem",
        "margin-sm": "1rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-dm-sans)", "DM Sans", "sans-serif"],
        headline: ["var(--font-dm-sans)", "DM Sans", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["DM Sans", "sans-serif"],
        "display-lg-mobile": ["DM Sans", "sans-serif"],
        "headline-lg": ["DM Sans", "sans-serif"],
        "headline-lg-mobile": ["DM Sans", "sans-serif"],
        "headline-md": ["DM Sans", "sans-serif"],
        "headline-sm": ["DM Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
      boxShadow: {
        whisper: "0 4px 20px -2px rgba(36, 91, 90, 0.05), 0 2px 6px -1px rgba(36, 91, 90, 0.03)",
        sanctuary: "0 8px 30px rgba(36, 51, 51, 0.06)",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(0.94)", opacity: "0.85" },
          "50%": { transform: "scale(1.18)", opacity: "1" },
        },
        pulseSlow: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        breathe: "breathe 4s ease-in-out infinite",
        "pulse-slow": "pulseSlow 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
